// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: beam.proto

package sharebase;

public final class Beam {
  private Beam() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BeamMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sharebase.BeamMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required sint32 version = 1;</code>
     */
    boolean hasVersion();
    /**
     * <code>required sint32 version = 1;</code>
     */
    int getVersion();

    /**
     * <code>optional sint64 workerhashid = 2;</code>
     */
    boolean hasWorkerhashid();
    /**
     * <code>optional sint64 workerhashid = 2;</code>
     */
    long getWorkerhashid();

    /**
     * <code>optional sint32 userid = 3;</code>
     */
    boolean hasUserid();
    /**
     * <code>optional sint32 userid = 3;</code>
     */
    int getUserid();

    /**
     * <code>optional sint32 status = 4;</code>
     */
    boolean hasStatus();
    /**
     * <code>optional sint32 status = 4;</code>
     */
    int getStatus();

    /**
     * <code>optional sint64 timestamp = 5;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>optional sint64 timestamp = 5;</code>
     */
    long getTimestamp();

    /**
     * <code>optional string ip = 6;</code>
     */
    boolean hasIp();
    /**
     * <code>optional string ip = 6;</code>
     */
    java.lang.String getIp();
    /**
     * <code>optional string ip = 6;</code>
     */
    com.google.protobuf.ByteString
        getIpBytes();

    /**
     * <code>optional uint64 inputprefix = 7;</code>
     */
    boolean hasInputprefix();
    /**
     * <code>optional uint64 inputprefix = 7;</code>
     */
    long getInputprefix();

    /**
     * <code>optional uint64 sharediff = 8;</code>
     */
    boolean hasSharediff();
    /**
     * <code>optional uint64 sharediff = 8;</code>
     */
    long getSharediff();

    /**
     * <code>optional uint64 blockbits = 9;</code>
     */
    boolean hasBlockbits();
    /**
     * <code>optional uint64 blockbits = 9;</code>
     */
    long getBlockbits();

    /**
     * <code>optional uint32 height = 10;</code>
     */
    boolean hasHeight();
    /**
     * <code>optional uint32 height = 10;</code>
     */
    int getHeight();

    /**
     * <code>optional uint64 nonce = 11;</code>
     */
    boolean hasNonce();
    /**
     * <code>optional uint64 nonce = 11;</code>
     */
    long getNonce();

    /**
     * <code>optional uint32 sessionid = 12;</code>
     */
    boolean hasSessionid();
    /**
     * <code>optional uint32 sessionid = 12;</code>
     */
    int getSessionid();

    /**
     * <code>optional uint32 outputhash = 13;</code>
     */
    boolean hasOutputhash();
    /**
     * <code>optional uint32 outputhash = 13;</code>
     */
    int getOutputhash();

    /**
     * <pre>
     * Extended uid in single-user mode. May not be set.
     * </pre>
     *
     * <code>optional sint32 extuserid = 14;</code>
     */
    boolean hasExtuserid();
    /**
     * <pre>
     * Extended uid in single-user mode. May not be set.
     * </pre>
     *
     * <code>optional sint32 extuserid = 14;</code>
     */
    int getExtuserid();

    /**
     * <code>optional uint32 bitsreached = 15;</code>
     */
    boolean hasBitsreached();
    /**
     * <code>optional uint32 bitsreached = 15;</code>
     */
    int getBitsreached();
  }
  /**
   * Protobuf type {@code sharebase.BeamMsg}
   */
  public  static final class BeamMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sharebase.BeamMsg)
      BeamMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BeamMsg.newBuilder() to construct.
    private BeamMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BeamMsg() {
      version_ = 0;
      workerhashid_ = 0L;
      userid_ = 0;
      status_ = 0;
      timestamp_ = 0L;
      ip_ = "";
      inputprefix_ = 0L;
      sharediff_ = 0L;
      blockbits_ = 0L;
      height_ = 0;
      nonce_ = 0L;
      sessionid_ = 0;
      outputhash_ = 0;
      extuserid_ = 0;
      bitsreached_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BeamMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              version_ = input.readSInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              workerhashid_ = input.readSInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              userid_ = input.readSInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              status_ = input.readSInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              timestamp_ = input.readSInt64();
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              ip_ = bs;
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              inputprefix_ = input.readUInt64();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              sharediff_ = input.readUInt64();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              blockbits_ = input.readUInt64();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              height_ = input.readUInt32();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              nonce_ = input.readUInt64();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              sessionid_ = input.readUInt32();
              break;
            }
            case 104: {
              bitField0_ |= 0x00001000;
              outputhash_ = input.readUInt32();
              break;
            }
            case 112: {
              bitField0_ |= 0x00002000;
              extuserid_ = input.readSInt32();
              break;
            }
            case 120: {
              bitField0_ |= 0x00004000;
              bitsreached_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sharebase.Beam.internal_static_sharebase_BeamMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sharebase.Beam.internal_static_sharebase_BeamMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sharebase.Beam.BeamMsg.class, sharebase.Beam.BeamMsg.Builder.class);
    }

    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>required sint32 version = 1;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required sint32 version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }

    public static final int WORKERHASHID_FIELD_NUMBER = 2;
    private long workerhashid_;
    /**
     * <code>optional sint64 workerhashid = 2;</code>
     */
    public boolean hasWorkerhashid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional sint64 workerhashid = 2;</code>
     */
    public long getWorkerhashid() {
      return workerhashid_;
    }

    public static final int USERID_FIELD_NUMBER = 3;
    private int userid_;
    /**
     * <code>optional sint32 userid = 3;</code>
     */
    public boolean hasUserid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional sint32 userid = 3;</code>
     */
    public int getUserid() {
      return userid_;
    }

    public static final int STATUS_FIELD_NUMBER = 4;
    private int status_;
    /**
     * <code>optional sint32 status = 4;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional sint32 status = 4;</code>
     */
    public int getStatus() {
      return status_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 5;
    private long timestamp_;
    /**
     * <code>optional sint64 timestamp = 5;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional sint64 timestamp = 5;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int IP_FIELD_NUMBER = 6;
    private volatile java.lang.Object ip_;
    /**
     * <code>optional string ip = 6;</code>
     */
    public boolean hasIp() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string ip = 6;</code>
     */
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ip_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string ip = 6;</code>
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INPUTPREFIX_FIELD_NUMBER = 7;
    private long inputprefix_;
    /**
     * <code>optional uint64 inputprefix = 7;</code>
     */
    public boolean hasInputprefix() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional uint64 inputprefix = 7;</code>
     */
    public long getInputprefix() {
      return inputprefix_;
    }

    public static final int SHAREDIFF_FIELD_NUMBER = 8;
    private long sharediff_;
    /**
     * <code>optional uint64 sharediff = 8;</code>
     */
    public boolean hasSharediff() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional uint64 sharediff = 8;</code>
     */
    public long getSharediff() {
      return sharediff_;
    }

    public static final int BLOCKBITS_FIELD_NUMBER = 9;
    private long blockbits_;
    /**
     * <code>optional uint64 blockbits = 9;</code>
     */
    public boolean hasBlockbits() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional uint64 blockbits = 9;</code>
     */
    public long getBlockbits() {
      return blockbits_;
    }

    public static final int HEIGHT_FIELD_NUMBER = 10;
    private int height_;
    /**
     * <code>optional uint32 height = 10;</code>
     */
    public boolean hasHeight() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional uint32 height = 10;</code>
     */
    public int getHeight() {
      return height_;
    }

    public static final int NONCE_FIELD_NUMBER = 11;
    private long nonce_;
    /**
     * <code>optional uint64 nonce = 11;</code>
     */
    public boolean hasNonce() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional uint64 nonce = 11;</code>
     */
    public long getNonce() {
      return nonce_;
    }

    public static final int SESSIONID_FIELD_NUMBER = 12;
    private int sessionid_;
    /**
     * <code>optional uint32 sessionid = 12;</code>
     */
    public boolean hasSessionid() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional uint32 sessionid = 12;</code>
     */
    public int getSessionid() {
      return sessionid_;
    }

    public static final int OUTPUTHASH_FIELD_NUMBER = 13;
    private int outputhash_;
    /**
     * <code>optional uint32 outputhash = 13;</code>
     */
    public boolean hasOutputhash() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional uint32 outputhash = 13;</code>
     */
    public int getOutputhash() {
      return outputhash_;
    }

    public static final int EXTUSERID_FIELD_NUMBER = 14;
    private int extuserid_;
    /**
     * <pre>
     * Extended uid in single-user mode. May not be set.
     * </pre>
     *
     * <code>optional sint32 extuserid = 14;</code>
     */
    public boolean hasExtuserid() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <pre>
     * Extended uid in single-user mode. May not be set.
     * </pre>
     *
     * <code>optional sint32 extuserid = 14;</code>
     */
    public int getExtuserid() {
      return extuserid_;
    }

    public static final int BITSREACHED_FIELD_NUMBER = 15;
    private int bitsreached_;
    /**
     * <code>optional uint32 bitsreached = 15;</code>
     */
    public boolean hasBitsreached() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    /**
     * <code>optional uint32 bitsreached = 15;</code>
     */
    public int getBitsreached() {
      return bitsreached_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeSInt32(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeSInt64(2, workerhashid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeSInt32(3, userid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeSInt32(4, status_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeSInt64(5, timestamp_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, ip_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeUInt64(7, inputprefix_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeUInt64(8, sharediff_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeUInt64(9, blockbits_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeUInt32(10, height_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeUInt64(11, nonce_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeUInt32(12, sessionid_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeUInt32(13, outputhash_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeSInt32(14, extuserid_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeUInt32(15, bitsreached_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(2, workerhashid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(3, userid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(4, status_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(5, timestamp_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, ip_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(7, inputprefix_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(8, sharediff_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(9, blockbits_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(10, height_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(11, nonce_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(12, sessionid_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(13, outputhash_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(14, extuserid_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(15, bitsreached_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sharebase.Beam.BeamMsg)) {
        return super.equals(obj);
      }
      sharebase.Beam.BeamMsg other = (sharebase.Beam.BeamMsg) obj;

      boolean result = true;
      result = result && (hasVersion() == other.hasVersion());
      if (hasVersion()) {
        result = result && (getVersion()
            == other.getVersion());
      }
      result = result && (hasWorkerhashid() == other.hasWorkerhashid());
      if (hasWorkerhashid()) {
        result = result && (getWorkerhashid()
            == other.getWorkerhashid());
      }
      result = result && (hasUserid() == other.hasUserid());
      if (hasUserid()) {
        result = result && (getUserid()
            == other.getUserid());
      }
      result = result && (hasStatus() == other.hasStatus());
      if (hasStatus()) {
        result = result && (getStatus()
            == other.getStatus());
      }
      result = result && (hasTimestamp() == other.hasTimestamp());
      if (hasTimestamp()) {
        result = result && (getTimestamp()
            == other.getTimestamp());
      }
      result = result && (hasIp() == other.hasIp());
      if (hasIp()) {
        result = result && getIp()
            .equals(other.getIp());
      }
      result = result && (hasInputprefix() == other.hasInputprefix());
      if (hasInputprefix()) {
        result = result && (getInputprefix()
            == other.getInputprefix());
      }
      result = result && (hasSharediff() == other.hasSharediff());
      if (hasSharediff()) {
        result = result && (getSharediff()
            == other.getSharediff());
      }
      result = result && (hasBlockbits() == other.hasBlockbits());
      if (hasBlockbits()) {
        result = result && (getBlockbits()
            == other.getBlockbits());
      }
      result = result && (hasHeight() == other.hasHeight());
      if (hasHeight()) {
        result = result && (getHeight()
            == other.getHeight());
      }
      result = result && (hasNonce() == other.hasNonce());
      if (hasNonce()) {
        result = result && (getNonce()
            == other.getNonce());
      }
      result = result && (hasSessionid() == other.hasSessionid());
      if (hasSessionid()) {
        result = result && (getSessionid()
            == other.getSessionid());
      }
      result = result && (hasOutputhash() == other.hasOutputhash());
      if (hasOutputhash()) {
        result = result && (getOutputhash()
            == other.getOutputhash());
      }
      result = result && (hasExtuserid() == other.hasExtuserid());
      if (hasExtuserid()) {
        result = result && (getExtuserid()
            == other.getExtuserid());
      }
      result = result && (hasBitsreached() == other.hasBitsreached());
      if (hasBitsreached()) {
        result = result && (getBitsreached()
            == other.getBitsreached());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasVersion()) {
        hash = (37 * hash) + VERSION_FIELD_NUMBER;
        hash = (53 * hash) + getVersion();
      }
      if (hasWorkerhashid()) {
        hash = (37 * hash) + WORKERHASHID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getWorkerhashid());
      }
      if (hasUserid()) {
        hash = (37 * hash) + USERID_FIELD_NUMBER;
        hash = (53 * hash) + getUserid();
      }
      if (hasStatus()) {
        hash = (37 * hash) + STATUS_FIELD_NUMBER;
        hash = (53 * hash) + getStatus();
      }
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTimestamp());
      }
      if (hasIp()) {
        hash = (37 * hash) + IP_FIELD_NUMBER;
        hash = (53 * hash) + getIp().hashCode();
      }
      if (hasInputprefix()) {
        hash = (37 * hash) + INPUTPREFIX_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getInputprefix());
      }
      if (hasSharediff()) {
        hash = (37 * hash) + SHAREDIFF_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getSharediff());
      }
      if (hasBlockbits()) {
        hash = (37 * hash) + BLOCKBITS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getBlockbits());
      }
      if (hasHeight()) {
        hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
        hash = (53 * hash) + getHeight();
      }
      if (hasNonce()) {
        hash = (37 * hash) + NONCE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getNonce());
      }
      if (hasSessionid()) {
        hash = (37 * hash) + SESSIONID_FIELD_NUMBER;
        hash = (53 * hash) + getSessionid();
      }
      if (hasOutputhash()) {
        hash = (37 * hash) + OUTPUTHASH_FIELD_NUMBER;
        hash = (53 * hash) + getOutputhash();
      }
      if (hasExtuserid()) {
        hash = (37 * hash) + EXTUSERID_FIELD_NUMBER;
        hash = (53 * hash) + getExtuserid();
      }
      if (hasBitsreached()) {
        hash = (37 * hash) + BITSREACHED_FIELD_NUMBER;
        hash = (53 * hash) + getBitsreached();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sharebase.Beam.BeamMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sharebase.Beam.BeamMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sharebase.Beam.BeamMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sharebase.Beam.BeamMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sharebase.Beam.BeamMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sharebase.Beam.BeamMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sharebase.Beam.BeamMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sharebase.Beam.BeamMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static sharebase.Beam.BeamMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static sharebase.Beam.BeamMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sharebase.Beam.BeamMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sharebase.Beam.BeamMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sharebase.Beam.BeamMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sharebase.BeamMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sharebase.BeamMsg)
        sharebase.Beam.BeamMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sharebase.Beam.internal_static_sharebase_BeamMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sharebase.Beam.internal_static_sharebase_BeamMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sharebase.Beam.BeamMsg.class, sharebase.Beam.BeamMsg.Builder.class);
      }

      // Construct using sharebase.Beam.BeamMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        workerhashid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        userid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        ip_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        inputprefix_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        sharediff_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000080);
        blockbits_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000100);
        height_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        nonce_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000400);
        sessionid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000800);
        outputhash_ = 0;
        bitField0_ = (bitField0_ & ~0x00001000);
        extuserid_ = 0;
        bitField0_ = (bitField0_ & ~0x00002000);
        bitsreached_ = 0;
        bitField0_ = (bitField0_ & ~0x00004000);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sharebase.Beam.internal_static_sharebase_BeamMsg_descriptor;
      }

      @java.lang.Override
      public sharebase.Beam.BeamMsg getDefaultInstanceForType() {
        return sharebase.Beam.BeamMsg.getDefaultInstance();
      }

      @java.lang.Override
      public sharebase.Beam.BeamMsg build() {
        sharebase.Beam.BeamMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public sharebase.Beam.BeamMsg buildPartial() {
        sharebase.Beam.BeamMsg result = new sharebase.Beam.BeamMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.workerhashid_ = workerhashid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.userid_ = userid_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.ip_ = ip_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.inputprefix_ = inputprefix_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.sharediff_ = sharediff_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.blockbits_ = blockbits_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.height_ = height_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.nonce_ = nonce_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.sessionid_ = sessionid_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.outputhash_ = outputhash_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.extuserid_ = extuserid_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.bitsreached_ = bitsreached_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sharebase.Beam.BeamMsg) {
          return mergeFrom((sharebase.Beam.BeamMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sharebase.Beam.BeamMsg other) {
        if (other == sharebase.Beam.BeamMsg.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasWorkerhashid()) {
          setWorkerhashid(other.getWorkerhashid());
        }
        if (other.hasUserid()) {
          setUserid(other.getUserid());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasIp()) {
          bitField0_ |= 0x00000020;
          ip_ = other.ip_;
          onChanged();
        }
        if (other.hasInputprefix()) {
          setInputprefix(other.getInputprefix());
        }
        if (other.hasSharediff()) {
          setSharediff(other.getSharediff());
        }
        if (other.hasBlockbits()) {
          setBlockbits(other.getBlockbits());
        }
        if (other.hasHeight()) {
          setHeight(other.getHeight());
        }
        if (other.hasNonce()) {
          setNonce(other.getNonce());
        }
        if (other.hasSessionid()) {
          setSessionid(other.getSessionid());
        }
        if (other.hasOutputhash()) {
          setOutputhash(other.getOutputhash());
        }
        if (other.hasExtuserid()) {
          setExtuserid(other.getExtuserid());
        }
        if (other.hasBitsreached()) {
          setBitsreached(other.getBitsreached());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasVersion()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        sharebase.Beam.BeamMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (sharebase.Beam.BeamMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int version_ ;
      /**
       * <code>required sint32 version = 1;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required sint32 version = 1;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>required sint32 version = 1;</code>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required sint32 version = 1;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0;
        onChanged();
        return this;
      }

      private long workerhashid_ ;
      /**
       * <code>optional sint64 workerhashid = 2;</code>
       */
      public boolean hasWorkerhashid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional sint64 workerhashid = 2;</code>
       */
      public long getWorkerhashid() {
        return workerhashid_;
      }
      /**
       * <code>optional sint64 workerhashid = 2;</code>
       */
      public Builder setWorkerhashid(long value) {
        bitField0_ |= 0x00000002;
        workerhashid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint64 workerhashid = 2;</code>
       */
      public Builder clearWorkerhashid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        workerhashid_ = 0L;
        onChanged();
        return this;
      }

      private int userid_ ;
      /**
       * <code>optional sint32 userid = 3;</code>
       */
      public boolean hasUserid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional sint32 userid = 3;</code>
       */
      public int getUserid() {
        return userid_;
      }
      /**
       * <code>optional sint32 userid = 3;</code>
       */
      public Builder setUserid(int value) {
        bitField0_ |= 0x00000004;
        userid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 userid = 3;</code>
       */
      public Builder clearUserid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        userid_ = 0;
        onChanged();
        return this;
      }

      private int status_ ;
      /**
       * <code>optional sint32 status = 4;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional sint32 status = 4;</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>optional sint32 status = 4;</code>
       */
      public Builder setStatus(int value) {
        bitField0_ |= 0x00000008;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 status = 4;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000008);
        status_ = 0;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>optional sint64 timestamp = 5;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional sint64 timestamp = 5;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional sint64 timestamp = 5;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000010;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint64 timestamp = 5;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000010);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object ip_ = "";
      /**
       * <code>optional string ip = 6;</code>
       */
      public boolean hasIp() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string ip = 6;</code>
       */
      public java.lang.String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ip_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ip = 6;</code>
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        java.lang.Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ip = 6;</code>
       */
      public Builder setIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ip = 6;</code>
       */
      public Builder clearIp() {
        bitField0_ = (bitField0_ & ~0x00000020);
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ip = 6;</code>
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        ip_ = value;
        onChanged();
        return this;
      }

      private long inputprefix_ ;
      /**
       * <code>optional uint64 inputprefix = 7;</code>
       */
      public boolean hasInputprefix() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional uint64 inputprefix = 7;</code>
       */
      public long getInputprefix() {
        return inputprefix_;
      }
      /**
       * <code>optional uint64 inputprefix = 7;</code>
       */
      public Builder setInputprefix(long value) {
        bitField0_ |= 0x00000040;
        inputprefix_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 inputprefix = 7;</code>
       */
      public Builder clearInputprefix() {
        bitField0_ = (bitField0_ & ~0x00000040);
        inputprefix_ = 0L;
        onChanged();
        return this;
      }

      private long sharediff_ ;
      /**
       * <code>optional uint64 sharediff = 8;</code>
       */
      public boolean hasSharediff() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional uint64 sharediff = 8;</code>
       */
      public long getSharediff() {
        return sharediff_;
      }
      /**
       * <code>optional uint64 sharediff = 8;</code>
       */
      public Builder setSharediff(long value) {
        bitField0_ |= 0x00000080;
        sharediff_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 sharediff = 8;</code>
       */
      public Builder clearSharediff() {
        bitField0_ = (bitField0_ & ~0x00000080);
        sharediff_ = 0L;
        onChanged();
        return this;
      }

      private long blockbits_ ;
      /**
       * <code>optional uint64 blockbits = 9;</code>
       */
      public boolean hasBlockbits() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional uint64 blockbits = 9;</code>
       */
      public long getBlockbits() {
        return blockbits_;
      }
      /**
       * <code>optional uint64 blockbits = 9;</code>
       */
      public Builder setBlockbits(long value) {
        bitField0_ |= 0x00000100;
        blockbits_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 blockbits = 9;</code>
       */
      public Builder clearBlockbits() {
        bitField0_ = (bitField0_ & ~0x00000100);
        blockbits_ = 0L;
        onChanged();
        return this;
      }

      private int height_ ;
      /**
       * <code>optional uint32 height = 10;</code>
       */
      public boolean hasHeight() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional uint32 height = 10;</code>
       */
      public int getHeight() {
        return height_;
      }
      /**
       * <code>optional uint32 height = 10;</code>
       */
      public Builder setHeight(int value) {
        bitField0_ |= 0x00000200;
        height_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 height = 10;</code>
       */
      public Builder clearHeight() {
        bitField0_ = (bitField0_ & ~0x00000200);
        height_ = 0;
        onChanged();
        return this;
      }

      private long nonce_ ;
      /**
       * <code>optional uint64 nonce = 11;</code>
       */
      public boolean hasNonce() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional uint64 nonce = 11;</code>
       */
      public long getNonce() {
        return nonce_;
      }
      /**
       * <code>optional uint64 nonce = 11;</code>
       */
      public Builder setNonce(long value) {
        bitField0_ |= 0x00000400;
        nonce_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 nonce = 11;</code>
       */
      public Builder clearNonce() {
        bitField0_ = (bitField0_ & ~0x00000400);
        nonce_ = 0L;
        onChanged();
        return this;
      }

      private int sessionid_ ;
      /**
       * <code>optional uint32 sessionid = 12;</code>
       */
      public boolean hasSessionid() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional uint32 sessionid = 12;</code>
       */
      public int getSessionid() {
        return sessionid_;
      }
      /**
       * <code>optional uint32 sessionid = 12;</code>
       */
      public Builder setSessionid(int value) {
        bitField0_ |= 0x00000800;
        sessionid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 sessionid = 12;</code>
       */
      public Builder clearSessionid() {
        bitField0_ = (bitField0_ & ~0x00000800);
        sessionid_ = 0;
        onChanged();
        return this;
      }

      private int outputhash_ ;
      /**
       * <code>optional uint32 outputhash = 13;</code>
       */
      public boolean hasOutputhash() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>optional uint32 outputhash = 13;</code>
       */
      public int getOutputhash() {
        return outputhash_;
      }
      /**
       * <code>optional uint32 outputhash = 13;</code>
       */
      public Builder setOutputhash(int value) {
        bitField0_ |= 0x00001000;
        outputhash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 outputhash = 13;</code>
       */
      public Builder clearOutputhash() {
        bitField0_ = (bitField0_ & ~0x00001000);
        outputhash_ = 0;
        onChanged();
        return this;
      }

      private int extuserid_ ;
      /**
       * <pre>
       * Extended uid in single-user mode. May not be set.
       * </pre>
       *
       * <code>optional sint32 extuserid = 14;</code>
       */
      public boolean hasExtuserid() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <pre>
       * Extended uid in single-user mode. May not be set.
       * </pre>
       *
       * <code>optional sint32 extuserid = 14;</code>
       */
      public int getExtuserid() {
        return extuserid_;
      }
      /**
       * <pre>
       * Extended uid in single-user mode. May not be set.
       * </pre>
       *
       * <code>optional sint32 extuserid = 14;</code>
       */
      public Builder setExtuserid(int value) {
        bitField0_ |= 0x00002000;
        extuserid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Extended uid in single-user mode. May not be set.
       * </pre>
       *
       * <code>optional sint32 extuserid = 14;</code>
       */
      public Builder clearExtuserid() {
        bitField0_ = (bitField0_ & ~0x00002000);
        extuserid_ = 0;
        onChanged();
        return this;
      }

      private int bitsreached_ ;
      /**
       * <code>optional uint32 bitsreached = 15;</code>
       */
      public boolean hasBitsreached() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      /**
       * <code>optional uint32 bitsreached = 15;</code>
       */
      public int getBitsreached() {
        return bitsreached_;
      }
      /**
       * <code>optional uint32 bitsreached = 15;</code>
       */
      public Builder setBitsreached(int value) {
        bitField0_ |= 0x00004000;
        bitsreached_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 bitsreached = 15;</code>
       */
      public Builder clearBitsreached() {
        bitField0_ = (bitField0_ & ~0x00004000);
        bitsreached_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sharebase.BeamMsg)
    }

    // @@protoc_insertion_point(class_scope:sharebase.BeamMsg)
    private static final sharebase.Beam.BeamMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sharebase.Beam.BeamMsg();
    }

    public static sharebase.Beam.BeamMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<BeamMsg>
        PARSER = new com.google.protobuf.AbstractParser<BeamMsg>() {
      @java.lang.Override
      public BeamMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BeamMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BeamMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BeamMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public sharebase.Beam.BeamMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sharebase_BeamMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sharebase_BeamMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nbeam.proto\022\tsharebase\"\230\002\n\007BeamMsg\022\017\n\007v" +
      "ersion\030\001 \002(\021\022\024\n\014workerhashid\030\002 \001(\022\022\016\n\006us" +
      "erid\030\003 \001(\021\022\016\n\006status\030\004 \001(\021\022\021\n\ttimestamp\030" +
      "\005 \001(\022\022\n\n\002ip\030\006 \001(\t\022\023\n\013inputprefix\030\007 \001(\004\022\021" +
      "\n\tsharediff\030\010 \001(\004\022\021\n\tblockbits\030\t \001(\004\022\016\n\006" +
      "height\030\n \001(\r\022\r\n\005nonce\030\013 \001(\004\022\021\n\tsessionid" +
      "\030\014 \001(\r\022\022\n\noutputhash\030\r \001(\r\022\021\n\textuserid\030" +
      "\016 \001(\021\022\023\n\013bitsreached\030\017 \001(\r"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_sharebase_BeamMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sharebase_BeamMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sharebase_BeamMsg_descriptor,
        new java.lang.String[] { "Version", "Workerhashid", "Userid", "Status", "Timestamp", "Ip", "Inputprefix", "Sharediff", "Blockbits", "Height", "Nonce", "Sessionid", "Outputhash", "Extuserid", "Bitsreached", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
