// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bitcoin.proto

package sharebase;

public final class Bitcoin {
  private Bitcoin() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BitcoinMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sharebase.BitcoinMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required sint32 version = 1;</code>
     */
    boolean hasVersion();
    /**
     * <code>required sint32 version = 1;</code>
     */
    int getVersion();

    /**
     * <code>optional sint64 workerhashid = 2;</code>
     */
    boolean hasWorkerhashid();
    /**
     * <code>optional sint64 workerhashid = 2;</code>
     */
    long getWorkerhashid();

    /**
     * <code>optional sint32 userid = 3;</code>
     */
    boolean hasUserid();
    /**
     * <code>optional sint32 userid = 3;</code>
     */
    int getUserid();

    /**
     * <code>optional sint32 status = 4;</code>
     */
    boolean hasStatus();
    /**
     * <code>optional sint32 status = 4;</code>
     */
    int getStatus();

    /**
     * <code>optional sint64 timestamp = 5;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>optional sint64 timestamp = 5;</code>
     */
    long getTimestamp();

    /**
     * <code>optional string ip = 6;</code>
     */
    boolean hasIp();
    /**
     * <code>optional string ip = 6;</code>
     */
    java.lang.String getIp();
    /**
     * <code>optional string ip = 6;</code>
     */
    com.google.protobuf.ByteString
        getIpBytes();

    /**
     * <code>optional uint64 jobid = 7;</code>
     */
    boolean hasJobid();
    /**
     * <code>optional uint64 jobid = 7;</code>
     */
    long getJobid();

    /**
     * <code>optional uint64 sharediff = 8;</code>
     */
    boolean hasSharediff();
    /**
     * <code>optional uint64 sharediff = 8;</code>
     */
    long getSharediff();

    /**
     * <code>optional uint32 blkbits = 9;</code>
     */
    boolean hasBlkbits();
    /**
     * <code>optional uint32 blkbits = 9;</code>
     */
    int getBlkbits();

    /**
     * <code>optional uint32 height = 10;</code>
     */
    boolean hasHeight();
    /**
     * <code>optional uint32 height = 10;</code>
     */
    int getHeight();

    /**
     * <code>optional uint32 nonce = 11;</code>
     */
    boolean hasNonce();
    /**
     * <code>optional uint32 nonce = 11;</code>
     */
    int getNonce();

    /**
     * <code>optional uint32 sessionid = 12;</code>
     */
    boolean hasSessionid();
    /**
     * <code>optional uint32 sessionid = 12;</code>
     */
    int getSessionid();

    /**
     * <code>optional uint32 versionmask = 13;</code>
     */
    boolean hasVersionmask();
    /**
     * <code>optional uint32 versionmask = 13;</code>
     */
    int getVersionmask();

    /**
     * <pre>
     * Extended uid in single-user mode. May not be set.
     * </pre>
     *
     * <code>optional sint32 extuserid = 14;</code>
     */
    boolean hasExtuserid();
    /**
     * <pre>
     * Extended uid in single-user mode. May not be set.
     * </pre>
     *
     * <code>optional sint32 extuserid = 14;</code>
     */
    int getExtuserid();

    /**
     * <code>optional uint32 bitsreached = 15;</code>
     */
    boolean hasBitsreached();
    /**
     * <code>optional uint32 bitsreached = 15;</code>
     */
    int getBitsreached();

    /**
     * <pre>
     * May not be set.
     * </pre>
     *
     * <code>optional uint32 grandnonce1 = 16;</code>
     */
    boolean hasGrandnonce1();
    /**
     * <pre>
     * May not be set.
     * </pre>
     *
     * <code>optional uint32 grandnonce1 = 16;</code>
     */
    int getGrandnonce1();

    /**
     * <pre>
     * May not be set.
     * </pre>
     *
     * <code>optional uint64 extranonce2 = 17;</code>
     */
    boolean hasExtranonce2();
    /**
     * <pre>
     * May not be set.
     * </pre>
     *
     * <code>optional uint64 extranonce2 = 17;</code>
     */
    long getExtranonce2();

    /**
     * <pre>
     * Timestamp in Bitcoin block header. May not be set.
     * </pre>
     *
     * <code>optional uint32 ntime = 18;</code>
     */
    boolean hasNtime();
    /**
     * <pre>
     * Timestamp in Bitcoin block header. May not be set.
     * </pre>
     *
     * <code>optional uint32 ntime = 18;</code>
     */
    int getNtime();

    /**
     * <pre>
     * Random bytes that changes per job. May not be set.
     * </pre>
     *
     * <code>optional uint32 jobnonce = 19;</code>
     */
    boolean hasJobnonce();
    /**
     * <pre>
     * Random bytes that changes per job. May not be set.
     * </pre>
     *
     * <code>optional uint32 jobnonce = 19;</code>
     */
    int getJobnonce();
  }
  /**
   * Protobuf type {@code sharebase.BitcoinMsg}
   */
  public  static final class BitcoinMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sharebase.BitcoinMsg)
      BitcoinMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BitcoinMsg.newBuilder() to construct.
    private BitcoinMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BitcoinMsg() {
      version_ = 0;
      workerhashid_ = 0L;
      userid_ = 0;
      status_ = 0;
      timestamp_ = 0L;
      ip_ = "";
      jobid_ = 0L;
      sharediff_ = 0L;
      blkbits_ = 0;
      height_ = 0;
      nonce_ = 0;
      sessionid_ = 0;
      versionmask_ = 0;
      extuserid_ = 0;
      bitsreached_ = 0;
      grandnonce1_ = 0;
      extranonce2_ = 0L;
      ntime_ = 0;
      jobnonce_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BitcoinMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              version_ = input.readSInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              workerhashid_ = input.readSInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              userid_ = input.readSInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              status_ = input.readSInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              timestamp_ = input.readSInt64();
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              ip_ = bs;
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              jobid_ = input.readUInt64();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              sharediff_ = input.readUInt64();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              blkbits_ = input.readUInt32();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              height_ = input.readUInt32();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              nonce_ = input.readUInt32();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              sessionid_ = input.readUInt32();
              break;
            }
            case 104: {
              bitField0_ |= 0x00001000;
              versionmask_ = input.readUInt32();
              break;
            }
            case 112: {
              bitField0_ |= 0x00002000;
              extuserid_ = input.readSInt32();
              break;
            }
            case 120: {
              bitField0_ |= 0x00004000;
              bitsreached_ = input.readUInt32();
              break;
            }
            case 128: {
              bitField0_ |= 0x00008000;
              grandnonce1_ = input.readUInt32();
              break;
            }
            case 136: {
              bitField0_ |= 0x00010000;
              extranonce2_ = input.readUInt64();
              break;
            }
            case 144: {
              bitField0_ |= 0x00020000;
              ntime_ = input.readUInt32();
              break;
            }
            case 152: {
              bitField0_ |= 0x00040000;
              jobnonce_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sharebase.Bitcoin.internal_static_sharebase_BitcoinMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sharebase.Bitcoin.internal_static_sharebase_BitcoinMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sharebase.Bitcoin.BitcoinMsg.class, sharebase.Bitcoin.BitcoinMsg.Builder.class);
    }

    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>required sint32 version = 1;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required sint32 version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }

    public static final int WORKERHASHID_FIELD_NUMBER = 2;
    private long workerhashid_;
    /**
     * <code>optional sint64 workerhashid = 2;</code>
     */
    public boolean hasWorkerhashid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional sint64 workerhashid = 2;</code>
     */
    public long getWorkerhashid() {
      return workerhashid_;
    }

    public static final int USERID_FIELD_NUMBER = 3;
    private int userid_;
    /**
     * <code>optional sint32 userid = 3;</code>
     */
    public boolean hasUserid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional sint32 userid = 3;</code>
     */
    public int getUserid() {
      return userid_;
    }

    public static final int STATUS_FIELD_NUMBER = 4;
    private int status_;
    /**
     * <code>optional sint32 status = 4;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional sint32 status = 4;</code>
     */
    public int getStatus() {
      return status_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 5;
    private long timestamp_;
    /**
     * <code>optional sint64 timestamp = 5;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional sint64 timestamp = 5;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int IP_FIELD_NUMBER = 6;
    private volatile java.lang.Object ip_;
    /**
     * <code>optional string ip = 6;</code>
     */
    public boolean hasIp() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string ip = 6;</code>
     */
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ip_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string ip = 6;</code>
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int JOBID_FIELD_NUMBER = 7;
    private long jobid_;
    /**
     * <code>optional uint64 jobid = 7;</code>
     */
    public boolean hasJobid() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional uint64 jobid = 7;</code>
     */
    public long getJobid() {
      return jobid_;
    }

    public static final int SHAREDIFF_FIELD_NUMBER = 8;
    private long sharediff_;
    /**
     * <code>optional uint64 sharediff = 8;</code>
     */
    public boolean hasSharediff() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional uint64 sharediff = 8;</code>
     */
    public long getSharediff() {
      return sharediff_;
    }

    public static final int BLKBITS_FIELD_NUMBER = 9;
    private int blkbits_;
    /**
     * <code>optional uint32 blkbits = 9;</code>
     */
    public boolean hasBlkbits() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional uint32 blkbits = 9;</code>
     */
    public int getBlkbits() {
      return blkbits_;
    }

    public static final int HEIGHT_FIELD_NUMBER = 10;
    private int height_;
    /**
     * <code>optional uint32 height = 10;</code>
     */
    public boolean hasHeight() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional uint32 height = 10;</code>
     */
    public int getHeight() {
      return height_;
    }

    public static final int NONCE_FIELD_NUMBER = 11;
    private int nonce_;
    /**
     * <code>optional uint32 nonce = 11;</code>
     */
    public boolean hasNonce() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional uint32 nonce = 11;</code>
     */
    public int getNonce() {
      return nonce_;
    }

    public static final int SESSIONID_FIELD_NUMBER = 12;
    private int sessionid_;
    /**
     * <code>optional uint32 sessionid = 12;</code>
     */
    public boolean hasSessionid() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional uint32 sessionid = 12;</code>
     */
    public int getSessionid() {
      return sessionid_;
    }

    public static final int VERSIONMASK_FIELD_NUMBER = 13;
    private int versionmask_;
    /**
     * <code>optional uint32 versionmask = 13;</code>
     */
    public boolean hasVersionmask() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional uint32 versionmask = 13;</code>
     */
    public int getVersionmask() {
      return versionmask_;
    }

    public static final int EXTUSERID_FIELD_NUMBER = 14;
    private int extuserid_;
    /**
     * <pre>
     * Extended uid in single-user mode. May not be set.
     * </pre>
     *
     * <code>optional sint32 extuserid = 14;</code>
     */
    public boolean hasExtuserid() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <pre>
     * Extended uid in single-user mode. May not be set.
     * </pre>
     *
     * <code>optional sint32 extuserid = 14;</code>
     */
    public int getExtuserid() {
      return extuserid_;
    }

    public static final int BITSREACHED_FIELD_NUMBER = 15;
    private int bitsreached_;
    /**
     * <code>optional uint32 bitsreached = 15;</code>
     */
    public boolean hasBitsreached() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    /**
     * <code>optional uint32 bitsreached = 15;</code>
     */
    public int getBitsreached() {
      return bitsreached_;
    }

    public static final int GRANDNONCE1_FIELD_NUMBER = 16;
    private int grandnonce1_;
    /**
     * <pre>
     * May not be set.
     * </pre>
     *
     * <code>optional uint32 grandnonce1 = 16;</code>
     */
    public boolean hasGrandnonce1() {
      return ((bitField0_ & 0x00008000) == 0x00008000);
    }
    /**
     * <pre>
     * May not be set.
     * </pre>
     *
     * <code>optional uint32 grandnonce1 = 16;</code>
     */
    public int getGrandnonce1() {
      return grandnonce1_;
    }

    public static final int EXTRANONCE2_FIELD_NUMBER = 17;
    private long extranonce2_;
    /**
     * <pre>
     * May not be set.
     * </pre>
     *
     * <code>optional uint64 extranonce2 = 17;</code>
     */
    public boolean hasExtranonce2() {
      return ((bitField0_ & 0x00010000) == 0x00010000);
    }
    /**
     * <pre>
     * May not be set.
     * </pre>
     *
     * <code>optional uint64 extranonce2 = 17;</code>
     */
    public long getExtranonce2() {
      return extranonce2_;
    }

    public static final int NTIME_FIELD_NUMBER = 18;
    private int ntime_;
    /**
     * <pre>
     * Timestamp in Bitcoin block header. May not be set.
     * </pre>
     *
     * <code>optional uint32 ntime = 18;</code>
     */
    public boolean hasNtime() {
      return ((bitField0_ & 0x00020000) == 0x00020000);
    }
    /**
     * <pre>
     * Timestamp in Bitcoin block header. May not be set.
     * </pre>
     *
     * <code>optional uint32 ntime = 18;</code>
     */
    public int getNtime() {
      return ntime_;
    }

    public static final int JOBNONCE_FIELD_NUMBER = 19;
    private int jobnonce_;
    /**
     * <pre>
     * Random bytes that changes per job. May not be set.
     * </pre>
     *
     * <code>optional uint32 jobnonce = 19;</code>
     */
    public boolean hasJobnonce() {
      return ((bitField0_ & 0x00040000) == 0x00040000);
    }
    /**
     * <pre>
     * Random bytes that changes per job. May not be set.
     * </pre>
     *
     * <code>optional uint32 jobnonce = 19;</code>
     */
    public int getJobnonce() {
      return jobnonce_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeSInt32(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeSInt64(2, workerhashid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeSInt32(3, userid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeSInt32(4, status_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeSInt64(5, timestamp_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, ip_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeUInt64(7, jobid_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeUInt64(8, sharediff_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeUInt32(9, blkbits_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeUInt32(10, height_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeUInt32(11, nonce_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeUInt32(12, sessionid_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeUInt32(13, versionmask_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeSInt32(14, extuserid_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeUInt32(15, bitsreached_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        output.writeUInt32(16, grandnonce1_);
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        output.writeUInt64(17, extranonce2_);
      }
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        output.writeUInt32(18, ntime_);
      }
      if (((bitField0_ & 0x00040000) == 0x00040000)) {
        output.writeUInt32(19, jobnonce_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(2, workerhashid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(3, userid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(4, status_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(5, timestamp_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, ip_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(7, jobid_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(8, sharediff_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(9, blkbits_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(10, height_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(11, nonce_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(12, sessionid_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(13, versionmask_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(14, extuserid_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(15, bitsreached_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(16, grandnonce1_);
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(17, extranonce2_);
      }
      if (((bitField0_ & 0x00020000) == 0x00020000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(18, ntime_);
      }
      if (((bitField0_ & 0x00040000) == 0x00040000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(19, jobnonce_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sharebase.Bitcoin.BitcoinMsg)) {
        return super.equals(obj);
      }
      sharebase.Bitcoin.BitcoinMsg other = (sharebase.Bitcoin.BitcoinMsg) obj;

      boolean result = true;
      result = result && (hasVersion() == other.hasVersion());
      if (hasVersion()) {
        result = result && (getVersion()
            == other.getVersion());
      }
      result = result && (hasWorkerhashid() == other.hasWorkerhashid());
      if (hasWorkerhashid()) {
        result = result && (getWorkerhashid()
            == other.getWorkerhashid());
      }
      result = result && (hasUserid() == other.hasUserid());
      if (hasUserid()) {
        result = result && (getUserid()
            == other.getUserid());
      }
      result = result && (hasStatus() == other.hasStatus());
      if (hasStatus()) {
        result = result && (getStatus()
            == other.getStatus());
      }
      result = result && (hasTimestamp() == other.hasTimestamp());
      if (hasTimestamp()) {
        result = result && (getTimestamp()
            == other.getTimestamp());
      }
      result = result && (hasIp() == other.hasIp());
      if (hasIp()) {
        result = result && getIp()
            .equals(other.getIp());
      }
      result = result && (hasJobid() == other.hasJobid());
      if (hasJobid()) {
        result = result && (getJobid()
            == other.getJobid());
      }
      result = result && (hasSharediff() == other.hasSharediff());
      if (hasSharediff()) {
        result = result && (getSharediff()
            == other.getSharediff());
      }
      result = result && (hasBlkbits() == other.hasBlkbits());
      if (hasBlkbits()) {
        result = result && (getBlkbits()
            == other.getBlkbits());
      }
      result = result && (hasHeight() == other.hasHeight());
      if (hasHeight()) {
        result = result && (getHeight()
            == other.getHeight());
      }
      result = result && (hasNonce() == other.hasNonce());
      if (hasNonce()) {
        result = result && (getNonce()
            == other.getNonce());
      }
      result = result && (hasSessionid() == other.hasSessionid());
      if (hasSessionid()) {
        result = result && (getSessionid()
            == other.getSessionid());
      }
      result = result && (hasVersionmask() == other.hasVersionmask());
      if (hasVersionmask()) {
        result = result && (getVersionmask()
            == other.getVersionmask());
      }
      result = result && (hasExtuserid() == other.hasExtuserid());
      if (hasExtuserid()) {
        result = result && (getExtuserid()
            == other.getExtuserid());
      }
      result = result && (hasBitsreached() == other.hasBitsreached());
      if (hasBitsreached()) {
        result = result && (getBitsreached()
            == other.getBitsreached());
      }
      result = result && (hasGrandnonce1() == other.hasGrandnonce1());
      if (hasGrandnonce1()) {
        result = result && (getGrandnonce1()
            == other.getGrandnonce1());
      }
      result = result && (hasExtranonce2() == other.hasExtranonce2());
      if (hasExtranonce2()) {
        result = result && (getExtranonce2()
            == other.getExtranonce2());
      }
      result = result && (hasNtime() == other.hasNtime());
      if (hasNtime()) {
        result = result && (getNtime()
            == other.getNtime());
      }
      result = result && (hasJobnonce() == other.hasJobnonce());
      if (hasJobnonce()) {
        result = result && (getJobnonce()
            == other.getJobnonce());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasVersion()) {
        hash = (37 * hash) + VERSION_FIELD_NUMBER;
        hash = (53 * hash) + getVersion();
      }
      if (hasWorkerhashid()) {
        hash = (37 * hash) + WORKERHASHID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getWorkerhashid());
      }
      if (hasUserid()) {
        hash = (37 * hash) + USERID_FIELD_NUMBER;
        hash = (53 * hash) + getUserid();
      }
      if (hasStatus()) {
        hash = (37 * hash) + STATUS_FIELD_NUMBER;
        hash = (53 * hash) + getStatus();
      }
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTimestamp());
      }
      if (hasIp()) {
        hash = (37 * hash) + IP_FIELD_NUMBER;
        hash = (53 * hash) + getIp().hashCode();
      }
      if (hasJobid()) {
        hash = (37 * hash) + JOBID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getJobid());
      }
      if (hasSharediff()) {
        hash = (37 * hash) + SHAREDIFF_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getSharediff());
      }
      if (hasBlkbits()) {
        hash = (37 * hash) + BLKBITS_FIELD_NUMBER;
        hash = (53 * hash) + getBlkbits();
      }
      if (hasHeight()) {
        hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
        hash = (53 * hash) + getHeight();
      }
      if (hasNonce()) {
        hash = (37 * hash) + NONCE_FIELD_NUMBER;
        hash = (53 * hash) + getNonce();
      }
      if (hasSessionid()) {
        hash = (37 * hash) + SESSIONID_FIELD_NUMBER;
        hash = (53 * hash) + getSessionid();
      }
      if (hasVersionmask()) {
        hash = (37 * hash) + VERSIONMASK_FIELD_NUMBER;
        hash = (53 * hash) + getVersionmask();
      }
      if (hasExtuserid()) {
        hash = (37 * hash) + EXTUSERID_FIELD_NUMBER;
        hash = (53 * hash) + getExtuserid();
      }
      if (hasBitsreached()) {
        hash = (37 * hash) + BITSREACHED_FIELD_NUMBER;
        hash = (53 * hash) + getBitsreached();
      }
      if (hasGrandnonce1()) {
        hash = (37 * hash) + GRANDNONCE1_FIELD_NUMBER;
        hash = (53 * hash) + getGrandnonce1();
      }
      if (hasExtranonce2()) {
        hash = (37 * hash) + EXTRANONCE2_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getExtranonce2());
      }
      if (hasNtime()) {
        hash = (37 * hash) + NTIME_FIELD_NUMBER;
        hash = (53 * hash) + getNtime();
      }
      if (hasJobnonce()) {
        hash = (37 * hash) + JOBNONCE_FIELD_NUMBER;
        hash = (53 * hash) + getJobnonce();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sharebase.Bitcoin.BitcoinMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sharebase.Bitcoin.BitcoinMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sharebase.Bitcoin.BitcoinMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sharebase.Bitcoin.BitcoinMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sharebase.Bitcoin.BitcoinMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sharebase.Bitcoin.BitcoinMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sharebase.Bitcoin.BitcoinMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sharebase.Bitcoin.BitcoinMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static sharebase.Bitcoin.BitcoinMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static sharebase.Bitcoin.BitcoinMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sharebase.Bitcoin.BitcoinMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sharebase.Bitcoin.BitcoinMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sharebase.Bitcoin.BitcoinMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sharebase.BitcoinMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sharebase.BitcoinMsg)
        sharebase.Bitcoin.BitcoinMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sharebase.Bitcoin.internal_static_sharebase_BitcoinMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sharebase.Bitcoin.internal_static_sharebase_BitcoinMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sharebase.Bitcoin.BitcoinMsg.class, sharebase.Bitcoin.BitcoinMsg.Builder.class);
      }

      // Construct using sharebase.Bitcoin.BitcoinMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        workerhashid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        userid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        ip_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        jobid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        sharediff_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000080);
        blkbits_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        height_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        nonce_ = 0;
        bitField0_ = (bitField0_ & ~0x00000400);
        sessionid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000800);
        versionmask_ = 0;
        bitField0_ = (bitField0_ & ~0x00001000);
        extuserid_ = 0;
        bitField0_ = (bitField0_ & ~0x00002000);
        bitsreached_ = 0;
        bitField0_ = (bitField0_ & ~0x00004000);
        grandnonce1_ = 0;
        bitField0_ = (bitField0_ & ~0x00008000);
        extranonce2_ = 0L;
        bitField0_ = (bitField0_ & ~0x00010000);
        ntime_ = 0;
        bitField0_ = (bitField0_ & ~0x00020000);
        jobnonce_ = 0;
        bitField0_ = (bitField0_ & ~0x00040000);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sharebase.Bitcoin.internal_static_sharebase_BitcoinMsg_descriptor;
      }

      @java.lang.Override
      public sharebase.Bitcoin.BitcoinMsg getDefaultInstanceForType() {
        return sharebase.Bitcoin.BitcoinMsg.getDefaultInstance();
      }

      @java.lang.Override
      public sharebase.Bitcoin.BitcoinMsg build() {
        sharebase.Bitcoin.BitcoinMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public sharebase.Bitcoin.BitcoinMsg buildPartial() {
        sharebase.Bitcoin.BitcoinMsg result = new sharebase.Bitcoin.BitcoinMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.workerhashid_ = workerhashid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.userid_ = userid_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.ip_ = ip_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.jobid_ = jobid_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.sharediff_ = sharediff_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.blkbits_ = blkbits_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.height_ = height_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.nonce_ = nonce_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.sessionid_ = sessionid_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.versionmask_ = versionmask_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.extuserid_ = extuserid_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.bitsreached_ = bitsreached_;
        if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
          to_bitField0_ |= 0x00008000;
        }
        result.grandnonce1_ = grandnonce1_;
        if (((from_bitField0_ & 0x00010000) == 0x00010000)) {
          to_bitField0_ |= 0x00010000;
        }
        result.extranonce2_ = extranonce2_;
        if (((from_bitField0_ & 0x00020000) == 0x00020000)) {
          to_bitField0_ |= 0x00020000;
        }
        result.ntime_ = ntime_;
        if (((from_bitField0_ & 0x00040000) == 0x00040000)) {
          to_bitField0_ |= 0x00040000;
        }
        result.jobnonce_ = jobnonce_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sharebase.Bitcoin.BitcoinMsg) {
          return mergeFrom((sharebase.Bitcoin.BitcoinMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sharebase.Bitcoin.BitcoinMsg other) {
        if (other == sharebase.Bitcoin.BitcoinMsg.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasWorkerhashid()) {
          setWorkerhashid(other.getWorkerhashid());
        }
        if (other.hasUserid()) {
          setUserid(other.getUserid());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasIp()) {
          bitField0_ |= 0x00000020;
          ip_ = other.ip_;
          onChanged();
        }
        if (other.hasJobid()) {
          setJobid(other.getJobid());
        }
        if (other.hasSharediff()) {
          setSharediff(other.getSharediff());
        }
        if (other.hasBlkbits()) {
          setBlkbits(other.getBlkbits());
        }
        if (other.hasHeight()) {
          setHeight(other.getHeight());
        }
        if (other.hasNonce()) {
          setNonce(other.getNonce());
        }
        if (other.hasSessionid()) {
          setSessionid(other.getSessionid());
        }
        if (other.hasVersionmask()) {
          setVersionmask(other.getVersionmask());
        }
        if (other.hasExtuserid()) {
          setExtuserid(other.getExtuserid());
        }
        if (other.hasBitsreached()) {
          setBitsreached(other.getBitsreached());
        }
        if (other.hasGrandnonce1()) {
          setGrandnonce1(other.getGrandnonce1());
        }
        if (other.hasExtranonce2()) {
          setExtranonce2(other.getExtranonce2());
        }
        if (other.hasNtime()) {
          setNtime(other.getNtime());
        }
        if (other.hasJobnonce()) {
          setJobnonce(other.getJobnonce());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasVersion()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        sharebase.Bitcoin.BitcoinMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (sharebase.Bitcoin.BitcoinMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int version_ ;
      /**
       * <code>required sint32 version = 1;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required sint32 version = 1;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>required sint32 version = 1;</code>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required sint32 version = 1;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0;
        onChanged();
        return this;
      }

      private long workerhashid_ ;
      /**
       * <code>optional sint64 workerhashid = 2;</code>
       */
      public boolean hasWorkerhashid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional sint64 workerhashid = 2;</code>
       */
      public long getWorkerhashid() {
        return workerhashid_;
      }
      /**
       * <code>optional sint64 workerhashid = 2;</code>
       */
      public Builder setWorkerhashid(long value) {
        bitField0_ |= 0x00000002;
        workerhashid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint64 workerhashid = 2;</code>
       */
      public Builder clearWorkerhashid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        workerhashid_ = 0L;
        onChanged();
        return this;
      }

      private int userid_ ;
      /**
       * <code>optional sint32 userid = 3;</code>
       */
      public boolean hasUserid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional sint32 userid = 3;</code>
       */
      public int getUserid() {
        return userid_;
      }
      /**
       * <code>optional sint32 userid = 3;</code>
       */
      public Builder setUserid(int value) {
        bitField0_ |= 0x00000004;
        userid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 userid = 3;</code>
       */
      public Builder clearUserid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        userid_ = 0;
        onChanged();
        return this;
      }

      private int status_ ;
      /**
       * <code>optional sint32 status = 4;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional sint32 status = 4;</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>optional sint32 status = 4;</code>
       */
      public Builder setStatus(int value) {
        bitField0_ |= 0x00000008;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 status = 4;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000008);
        status_ = 0;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>optional sint64 timestamp = 5;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional sint64 timestamp = 5;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional sint64 timestamp = 5;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000010;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint64 timestamp = 5;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000010);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object ip_ = "";
      /**
       * <code>optional string ip = 6;</code>
       */
      public boolean hasIp() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string ip = 6;</code>
       */
      public java.lang.String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ip_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ip = 6;</code>
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        java.lang.Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ip = 6;</code>
       */
      public Builder setIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ip = 6;</code>
       */
      public Builder clearIp() {
        bitField0_ = (bitField0_ & ~0x00000020);
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ip = 6;</code>
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        ip_ = value;
        onChanged();
        return this;
      }

      private long jobid_ ;
      /**
       * <code>optional uint64 jobid = 7;</code>
       */
      public boolean hasJobid() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional uint64 jobid = 7;</code>
       */
      public long getJobid() {
        return jobid_;
      }
      /**
       * <code>optional uint64 jobid = 7;</code>
       */
      public Builder setJobid(long value) {
        bitField0_ |= 0x00000040;
        jobid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 jobid = 7;</code>
       */
      public Builder clearJobid() {
        bitField0_ = (bitField0_ & ~0x00000040);
        jobid_ = 0L;
        onChanged();
        return this;
      }

      private long sharediff_ ;
      /**
       * <code>optional uint64 sharediff = 8;</code>
       */
      public boolean hasSharediff() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional uint64 sharediff = 8;</code>
       */
      public long getSharediff() {
        return sharediff_;
      }
      /**
       * <code>optional uint64 sharediff = 8;</code>
       */
      public Builder setSharediff(long value) {
        bitField0_ |= 0x00000080;
        sharediff_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 sharediff = 8;</code>
       */
      public Builder clearSharediff() {
        bitField0_ = (bitField0_ & ~0x00000080);
        sharediff_ = 0L;
        onChanged();
        return this;
      }

      private int blkbits_ ;
      /**
       * <code>optional uint32 blkbits = 9;</code>
       */
      public boolean hasBlkbits() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional uint32 blkbits = 9;</code>
       */
      public int getBlkbits() {
        return blkbits_;
      }
      /**
       * <code>optional uint32 blkbits = 9;</code>
       */
      public Builder setBlkbits(int value) {
        bitField0_ |= 0x00000100;
        blkbits_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 blkbits = 9;</code>
       */
      public Builder clearBlkbits() {
        bitField0_ = (bitField0_ & ~0x00000100);
        blkbits_ = 0;
        onChanged();
        return this;
      }

      private int height_ ;
      /**
       * <code>optional uint32 height = 10;</code>
       */
      public boolean hasHeight() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional uint32 height = 10;</code>
       */
      public int getHeight() {
        return height_;
      }
      /**
       * <code>optional uint32 height = 10;</code>
       */
      public Builder setHeight(int value) {
        bitField0_ |= 0x00000200;
        height_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 height = 10;</code>
       */
      public Builder clearHeight() {
        bitField0_ = (bitField0_ & ~0x00000200);
        height_ = 0;
        onChanged();
        return this;
      }

      private int nonce_ ;
      /**
       * <code>optional uint32 nonce = 11;</code>
       */
      public boolean hasNonce() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional uint32 nonce = 11;</code>
       */
      public int getNonce() {
        return nonce_;
      }
      /**
       * <code>optional uint32 nonce = 11;</code>
       */
      public Builder setNonce(int value) {
        bitField0_ |= 0x00000400;
        nonce_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 nonce = 11;</code>
       */
      public Builder clearNonce() {
        bitField0_ = (bitField0_ & ~0x00000400);
        nonce_ = 0;
        onChanged();
        return this;
      }

      private int sessionid_ ;
      /**
       * <code>optional uint32 sessionid = 12;</code>
       */
      public boolean hasSessionid() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional uint32 sessionid = 12;</code>
       */
      public int getSessionid() {
        return sessionid_;
      }
      /**
       * <code>optional uint32 sessionid = 12;</code>
       */
      public Builder setSessionid(int value) {
        bitField0_ |= 0x00000800;
        sessionid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 sessionid = 12;</code>
       */
      public Builder clearSessionid() {
        bitField0_ = (bitField0_ & ~0x00000800);
        sessionid_ = 0;
        onChanged();
        return this;
      }

      private int versionmask_ ;
      /**
       * <code>optional uint32 versionmask = 13;</code>
       */
      public boolean hasVersionmask() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>optional uint32 versionmask = 13;</code>
       */
      public int getVersionmask() {
        return versionmask_;
      }
      /**
       * <code>optional uint32 versionmask = 13;</code>
       */
      public Builder setVersionmask(int value) {
        bitField0_ |= 0x00001000;
        versionmask_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 versionmask = 13;</code>
       */
      public Builder clearVersionmask() {
        bitField0_ = (bitField0_ & ~0x00001000);
        versionmask_ = 0;
        onChanged();
        return this;
      }

      private int extuserid_ ;
      /**
       * <pre>
       * Extended uid in single-user mode. May not be set.
       * </pre>
       *
       * <code>optional sint32 extuserid = 14;</code>
       */
      public boolean hasExtuserid() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <pre>
       * Extended uid in single-user mode. May not be set.
       * </pre>
       *
       * <code>optional sint32 extuserid = 14;</code>
       */
      public int getExtuserid() {
        return extuserid_;
      }
      /**
       * <pre>
       * Extended uid in single-user mode. May not be set.
       * </pre>
       *
       * <code>optional sint32 extuserid = 14;</code>
       */
      public Builder setExtuserid(int value) {
        bitField0_ |= 0x00002000;
        extuserid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Extended uid in single-user mode. May not be set.
       * </pre>
       *
       * <code>optional sint32 extuserid = 14;</code>
       */
      public Builder clearExtuserid() {
        bitField0_ = (bitField0_ & ~0x00002000);
        extuserid_ = 0;
        onChanged();
        return this;
      }

      private int bitsreached_ ;
      /**
       * <code>optional uint32 bitsreached = 15;</code>
       */
      public boolean hasBitsreached() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      /**
       * <code>optional uint32 bitsreached = 15;</code>
       */
      public int getBitsreached() {
        return bitsreached_;
      }
      /**
       * <code>optional uint32 bitsreached = 15;</code>
       */
      public Builder setBitsreached(int value) {
        bitField0_ |= 0x00004000;
        bitsreached_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 bitsreached = 15;</code>
       */
      public Builder clearBitsreached() {
        bitField0_ = (bitField0_ & ~0x00004000);
        bitsreached_ = 0;
        onChanged();
        return this;
      }

      private int grandnonce1_ ;
      /**
       * <pre>
       * May not be set.
       * </pre>
       *
       * <code>optional uint32 grandnonce1 = 16;</code>
       */
      public boolean hasGrandnonce1() {
        return ((bitField0_ & 0x00008000) == 0x00008000);
      }
      /**
       * <pre>
       * May not be set.
       * </pre>
       *
       * <code>optional uint32 grandnonce1 = 16;</code>
       */
      public int getGrandnonce1() {
        return grandnonce1_;
      }
      /**
       * <pre>
       * May not be set.
       * </pre>
       *
       * <code>optional uint32 grandnonce1 = 16;</code>
       */
      public Builder setGrandnonce1(int value) {
        bitField0_ |= 0x00008000;
        grandnonce1_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * May not be set.
       * </pre>
       *
       * <code>optional uint32 grandnonce1 = 16;</code>
       */
      public Builder clearGrandnonce1() {
        bitField0_ = (bitField0_ & ~0x00008000);
        grandnonce1_ = 0;
        onChanged();
        return this;
      }

      private long extranonce2_ ;
      /**
       * <pre>
       * May not be set.
       * </pre>
       *
       * <code>optional uint64 extranonce2 = 17;</code>
       */
      public boolean hasExtranonce2() {
        return ((bitField0_ & 0x00010000) == 0x00010000);
      }
      /**
       * <pre>
       * May not be set.
       * </pre>
       *
       * <code>optional uint64 extranonce2 = 17;</code>
       */
      public long getExtranonce2() {
        return extranonce2_;
      }
      /**
       * <pre>
       * May not be set.
       * </pre>
       *
       * <code>optional uint64 extranonce2 = 17;</code>
       */
      public Builder setExtranonce2(long value) {
        bitField0_ |= 0x00010000;
        extranonce2_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * May not be set.
       * </pre>
       *
       * <code>optional uint64 extranonce2 = 17;</code>
       */
      public Builder clearExtranonce2() {
        bitField0_ = (bitField0_ & ~0x00010000);
        extranonce2_ = 0L;
        onChanged();
        return this;
      }

      private int ntime_ ;
      /**
       * <pre>
       * Timestamp in Bitcoin block header. May not be set.
       * </pre>
       *
       * <code>optional uint32 ntime = 18;</code>
       */
      public boolean hasNtime() {
        return ((bitField0_ & 0x00020000) == 0x00020000);
      }
      /**
       * <pre>
       * Timestamp in Bitcoin block header. May not be set.
       * </pre>
       *
       * <code>optional uint32 ntime = 18;</code>
       */
      public int getNtime() {
        return ntime_;
      }
      /**
       * <pre>
       * Timestamp in Bitcoin block header. May not be set.
       * </pre>
       *
       * <code>optional uint32 ntime = 18;</code>
       */
      public Builder setNtime(int value) {
        bitField0_ |= 0x00020000;
        ntime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Timestamp in Bitcoin block header. May not be set.
       * </pre>
       *
       * <code>optional uint32 ntime = 18;</code>
       */
      public Builder clearNtime() {
        bitField0_ = (bitField0_ & ~0x00020000);
        ntime_ = 0;
        onChanged();
        return this;
      }

      private int jobnonce_ ;
      /**
       * <pre>
       * Random bytes that changes per job. May not be set.
       * </pre>
       *
       * <code>optional uint32 jobnonce = 19;</code>
       */
      public boolean hasJobnonce() {
        return ((bitField0_ & 0x00040000) == 0x00040000);
      }
      /**
       * <pre>
       * Random bytes that changes per job. May not be set.
       * </pre>
       *
       * <code>optional uint32 jobnonce = 19;</code>
       */
      public int getJobnonce() {
        return jobnonce_;
      }
      /**
       * <pre>
       * Random bytes that changes per job. May not be set.
       * </pre>
       *
       * <code>optional uint32 jobnonce = 19;</code>
       */
      public Builder setJobnonce(int value) {
        bitField0_ |= 0x00040000;
        jobnonce_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Random bytes that changes per job. May not be set.
       * </pre>
       *
       * <code>optional uint32 jobnonce = 19;</code>
       */
      public Builder clearJobnonce() {
        bitField0_ = (bitField0_ & ~0x00040000);
        jobnonce_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sharebase.BitcoinMsg)
    }

    // @@protoc_insertion_point(class_scope:sharebase.BitcoinMsg)
    private static final sharebase.Bitcoin.BitcoinMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sharebase.Bitcoin.BitcoinMsg();
    }

    public static sharebase.Bitcoin.BitcoinMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<BitcoinMsg>
        PARSER = new com.google.protobuf.AbstractParser<BitcoinMsg>() {
      @java.lang.Override
      public BitcoinMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BitcoinMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BitcoinMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BitcoinMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public sharebase.Bitcoin.BitcoinMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sharebase_BitcoinMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sharebase_BitcoinMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rbitcoin.proto\022\tsharebase\"\337\002\n\nBitcoinMs" +
      "g\022\017\n\007version\030\001 \002(\021\022\024\n\014workerhashid\030\002 \001(\022" +
      "\022\016\n\006userid\030\003 \001(\021\022\016\n\006status\030\004 \001(\021\022\021\n\ttime" +
      "stamp\030\005 \001(\022\022\n\n\002ip\030\006 \001(\t\022\r\n\005jobid\030\007 \001(\004\022\021" +
      "\n\tsharediff\030\010 \001(\004\022\017\n\007blkbits\030\t \001(\r\022\016\n\006he" +
      "ight\030\n \001(\r\022\r\n\005nonce\030\013 \001(\r\022\021\n\tsessionid\030\014" +
      " \001(\r\022\023\n\013versionmask\030\r \001(\r\022\021\n\textuserid\030\016" +
      " \001(\021\022\023\n\013bitsreached\030\017 \001(\r\022\023\n\013grandnonce1" +
      "\030\020 \001(\r\022\023\n\013extranonce2\030\021 \001(\004\022\r\n\005ntime\030\022 \001" +
      "(\r\022\020\n\010jobnonce\030\023 \001(\r"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_sharebase_BitcoinMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sharebase_BitcoinMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sharebase_BitcoinMsg_descriptor,
        new java.lang.String[] { "Version", "Workerhashid", "Userid", "Status", "Timestamp", "Ip", "Jobid", "Sharediff", "Blkbits", "Height", "Nonce", "Sessionid", "Versionmask", "Extuserid", "Bitsreached", "Grandnonce1", "Extranonce2", "Ntime", "Jobnonce", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
