// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bytom.proto

package sharebase;

public final class Bytom {
  private Bytom() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BytomMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sharebase.BytomMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 version = 1;</code>
     */
    boolean hasVersion();
    /**
     * <code>required uint32 version = 1;</code>
     */
    int getVersion();

    /**
     * <code>optional uint64 jobid = 2;</code>
     */
    boolean hasJobid();
    /**
     * <code>optional uint64 jobid = 2;</code>
     */
    long getJobid();

    /**
     * <code>optional sint64 workerhashid = 3;</code>
     */
    boolean hasWorkerhashid();
    /**
     * <code>optional sint64 workerhashid = 3;</code>
     */
    long getWorkerhashid();

    /**
     * <code>optional sint64 timestamp = 4;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>optional sint64 timestamp = 4;</code>
     */
    long getTimestamp();

    /**
     * <code>optional uint64 sharediff = 5;</code>
     */
    boolean hasSharediff();
    /**
     * <code>optional uint64 sharediff = 5;</code>
     */
    long getSharediff();

    /**
     * <code>optional uint64 blkbits = 6;</code>
     */
    boolean hasBlkbits();
    /**
     * <code>optional uint64 blkbits = 6;</code>
     */
    long getBlkbits();

    /**
     * <code>optional uint64 height = 7;</code>
     */
    boolean hasHeight();
    /**
     * <code>optional uint64 height = 7;</code>
     */
    long getHeight();

    /**
     * <code>optional string ip = 8;</code>
     */
    boolean hasIp();
    /**
     * <code>optional string ip = 8;</code>
     */
    java.lang.String getIp();
    /**
     * <code>optional string ip = 8;</code>
     */
    com.google.protobuf.ByteString
        getIpBytes();

    /**
     * <code>optional bytes combinedHeader = 9;</code>
     */
    boolean hasCombinedHeader();
    /**
     * <code>optional bytes combinedHeader = 9;</code>
     */
    com.google.protobuf.ByteString getCombinedHeader();

    /**
     * <code>optional sint32 userid = 10;</code>
     */
    boolean hasUserid();
    /**
     * <code>optional sint32 userid = 10;</code>
     */
    int getUserid();

    /**
     * <code>optional sint32 status = 11;</code>
     */
    boolean hasStatus();
    /**
     * <code>optional sint32 status = 11;</code>
     */
    int getStatus();

    /**
     * <pre>
     * Extended uid in single-user mode. May not be set.
     * </pre>
     *
     * <code>optional sint32 extuserid = 12;</code>
     */
    boolean hasExtuserid();
    /**
     * <pre>
     * Extended uid in single-user mode. May not be set.
     * </pre>
     *
     * <code>optional sint32 extuserid = 12;</code>
     */
    int getExtuserid();

    /**
     * <code>optional uint32 bitsreached = 13;</code>
     */
    boolean hasBitsreached();
    /**
     * <code>optional uint32 bitsreached = 13;</code>
     */
    int getBitsreached();
  }
  /**
   * Protobuf type {@code sharebase.BytomMsg}
   */
  public  static final class BytomMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sharebase.BytomMsg)
      BytomMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BytomMsg.newBuilder() to construct.
    private BytomMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BytomMsg() {
      version_ = 0;
      jobid_ = 0L;
      workerhashid_ = 0L;
      timestamp_ = 0L;
      sharediff_ = 0L;
      blkbits_ = 0L;
      height_ = 0L;
      ip_ = "";
      combinedHeader_ = com.google.protobuf.ByteString.EMPTY;
      userid_ = 0;
      status_ = 0;
      extuserid_ = 0;
      bitsreached_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BytomMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              version_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              jobid_ = input.readUInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              workerhashid_ = input.readSInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              timestamp_ = input.readSInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              sharediff_ = input.readUInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              blkbits_ = input.readUInt64();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              height_ = input.readUInt64();
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              ip_ = bs;
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              combinedHeader_ = input.readBytes();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              userid_ = input.readSInt32();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              status_ = input.readSInt32();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              extuserid_ = input.readSInt32();
              break;
            }
            case 104: {
              bitField0_ |= 0x00001000;
              bitsreached_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sharebase.Bytom.internal_static_sharebase_BytomMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sharebase.Bytom.internal_static_sharebase_BytomMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sharebase.Bytom.BytomMsg.class, sharebase.Bytom.BytomMsg.Builder.class);
    }

    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>required uint32 version = 1;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }

    public static final int JOBID_FIELD_NUMBER = 2;
    private long jobid_;
    /**
     * <code>optional uint64 jobid = 2;</code>
     */
    public boolean hasJobid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint64 jobid = 2;</code>
     */
    public long getJobid() {
      return jobid_;
    }

    public static final int WORKERHASHID_FIELD_NUMBER = 3;
    private long workerhashid_;
    /**
     * <code>optional sint64 workerhashid = 3;</code>
     */
    public boolean hasWorkerhashid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional sint64 workerhashid = 3;</code>
     */
    public long getWorkerhashid() {
      return workerhashid_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 4;
    private long timestamp_;
    /**
     * <code>optional sint64 timestamp = 4;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional sint64 timestamp = 4;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int SHAREDIFF_FIELD_NUMBER = 5;
    private long sharediff_;
    /**
     * <code>optional uint64 sharediff = 5;</code>
     */
    public boolean hasSharediff() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional uint64 sharediff = 5;</code>
     */
    public long getSharediff() {
      return sharediff_;
    }

    public static final int BLKBITS_FIELD_NUMBER = 6;
    private long blkbits_;
    /**
     * <code>optional uint64 blkbits = 6;</code>
     */
    public boolean hasBlkbits() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional uint64 blkbits = 6;</code>
     */
    public long getBlkbits() {
      return blkbits_;
    }

    public static final int HEIGHT_FIELD_NUMBER = 7;
    private long height_;
    /**
     * <code>optional uint64 height = 7;</code>
     */
    public boolean hasHeight() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional uint64 height = 7;</code>
     */
    public long getHeight() {
      return height_;
    }

    public static final int IP_FIELD_NUMBER = 8;
    private volatile java.lang.Object ip_;
    /**
     * <code>optional string ip = 8;</code>
     */
    public boolean hasIp() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string ip = 8;</code>
     */
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ip_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string ip = 8;</code>
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMBINEDHEADER_FIELD_NUMBER = 9;
    private com.google.protobuf.ByteString combinedHeader_;
    /**
     * <code>optional bytes combinedHeader = 9;</code>
     */
    public boolean hasCombinedHeader() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional bytes combinedHeader = 9;</code>
     */
    public com.google.protobuf.ByteString getCombinedHeader() {
      return combinedHeader_;
    }

    public static final int USERID_FIELD_NUMBER = 10;
    private int userid_;
    /**
     * <code>optional sint32 userid = 10;</code>
     */
    public boolean hasUserid() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional sint32 userid = 10;</code>
     */
    public int getUserid() {
      return userid_;
    }

    public static final int STATUS_FIELD_NUMBER = 11;
    private int status_;
    /**
     * <code>optional sint32 status = 11;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional sint32 status = 11;</code>
     */
    public int getStatus() {
      return status_;
    }

    public static final int EXTUSERID_FIELD_NUMBER = 12;
    private int extuserid_;
    /**
     * <pre>
     * Extended uid in single-user mode. May not be set.
     * </pre>
     *
     * <code>optional sint32 extuserid = 12;</code>
     */
    public boolean hasExtuserid() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <pre>
     * Extended uid in single-user mode. May not be set.
     * </pre>
     *
     * <code>optional sint32 extuserid = 12;</code>
     */
    public int getExtuserid() {
      return extuserid_;
    }

    public static final int BITSREACHED_FIELD_NUMBER = 13;
    private int bitsreached_;
    /**
     * <code>optional uint32 bitsreached = 13;</code>
     */
    public boolean hasBitsreached() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional uint32 bitsreached = 13;</code>
     */
    public int getBitsreached() {
      return bitsreached_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, jobid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeSInt64(3, workerhashid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeSInt64(4, timestamp_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt64(5, sharediff_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeUInt64(6, blkbits_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeUInt64(7, height_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, ip_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, combinedHeader_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeSInt32(10, userid_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeSInt32(11, status_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeSInt32(12, extuserid_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeUInt32(13, bitsreached_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, jobid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(3, workerhashid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(4, timestamp_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, sharediff_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(6, blkbits_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(7, height_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, ip_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, combinedHeader_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(10, userid_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(11, status_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(12, extuserid_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(13, bitsreached_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sharebase.Bytom.BytomMsg)) {
        return super.equals(obj);
      }
      sharebase.Bytom.BytomMsg other = (sharebase.Bytom.BytomMsg) obj;

      boolean result = true;
      result = result && (hasVersion() == other.hasVersion());
      if (hasVersion()) {
        result = result && (getVersion()
            == other.getVersion());
      }
      result = result && (hasJobid() == other.hasJobid());
      if (hasJobid()) {
        result = result && (getJobid()
            == other.getJobid());
      }
      result = result && (hasWorkerhashid() == other.hasWorkerhashid());
      if (hasWorkerhashid()) {
        result = result && (getWorkerhashid()
            == other.getWorkerhashid());
      }
      result = result && (hasTimestamp() == other.hasTimestamp());
      if (hasTimestamp()) {
        result = result && (getTimestamp()
            == other.getTimestamp());
      }
      result = result && (hasSharediff() == other.hasSharediff());
      if (hasSharediff()) {
        result = result && (getSharediff()
            == other.getSharediff());
      }
      result = result && (hasBlkbits() == other.hasBlkbits());
      if (hasBlkbits()) {
        result = result && (getBlkbits()
            == other.getBlkbits());
      }
      result = result && (hasHeight() == other.hasHeight());
      if (hasHeight()) {
        result = result && (getHeight()
            == other.getHeight());
      }
      result = result && (hasIp() == other.hasIp());
      if (hasIp()) {
        result = result && getIp()
            .equals(other.getIp());
      }
      result = result && (hasCombinedHeader() == other.hasCombinedHeader());
      if (hasCombinedHeader()) {
        result = result && getCombinedHeader()
            .equals(other.getCombinedHeader());
      }
      result = result && (hasUserid() == other.hasUserid());
      if (hasUserid()) {
        result = result && (getUserid()
            == other.getUserid());
      }
      result = result && (hasStatus() == other.hasStatus());
      if (hasStatus()) {
        result = result && (getStatus()
            == other.getStatus());
      }
      result = result && (hasExtuserid() == other.hasExtuserid());
      if (hasExtuserid()) {
        result = result && (getExtuserid()
            == other.getExtuserid());
      }
      result = result && (hasBitsreached() == other.hasBitsreached());
      if (hasBitsreached()) {
        result = result && (getBitsreached()
            == other.getBitsreached());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasVersion()) {
        hash = (37 * hash) + VERSION_FIELD_NUMBER;
        hash = (53 * hash) + getVersion();
      }
      if (hasJobid()) {
        hash = (37 * hash) + JOBID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getJobid());
      }
      if (hasWorkerhashid()) {
        hash = (37 * hash) + WORKERHASHID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getWorkerhashid());
      }
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTimestamp());
      }
      if (hasSharediff()) {
        hash = (37 * hash) + SHAREDIFF_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getSharediff());
      }
      if (hasBlkbits()) {
        hash = (37 * hash) + BLKBITS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getBlkbits());
      }
      if (hasHeight()) {
        hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getHeight());
      }
      if (hasIp()) {
        hash = (37 * hash) + IP_FIELD_NUMBER;
        hash = (53 * hash) + getIp().hashCode();
      }
      if (hasCombinedHeader()) {
        hash = (37 * hash) + COMBINEDHEADER_FIELD_NUMBER;
        hash = (53 * hash) + getCombinedHeader().hashCode();
      }
      if (hasUserid()) {
        hash = (37 * hash) + USERID_FIELD_NUMBER;
        hash = (53 * hash) + getUserid();
      }
      if (hasStatus()) {
        hash = (37 * hash) + STATUS_FIELD_NUMBER;
        hash = (53 * hash) + getStatus();
      }
      if (hasExtuserid()) {
        hash = (37 * hash) + EXTUSERID_FIELD_NUMBER;
        hash = (53 * hash) + getExtuserid();
      }
      if (hasBitsreached()) {
        hash = (37 * hash) + BITSREACHED_FIELD_NUMBER;
        hash = (53 * hash) + getBitsreached();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sharebase.Bytom.BytomMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sharebase.Bytom.BytomMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sharebase.Bytom.BytomMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sharebase.Bytom.BytomMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sharebase.Bytom.BytomMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sharebase.Bytom.BytomMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sharebase.Bytom.BytomMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sharebase.Bytom.BytomMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static sharebase.Bytom.BytomMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static sharebase.Bytom.BytomMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sharebase.Bytom.BytomMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sharebase.Bytom.BytomMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sharebase.Bytom.BytomMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sharebase.BytomMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sharebase.BytomMsg)
        sharebase.Bytom.BytomMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sharebase.Bytom.internal_static_sharebase_BytomMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sharebase.Bytom.internal_static_sharebase_BytomMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sharebase.Bytom.BytomMsg.class, sharebase.Bytom.BytomMsg.Builder.class);
      }

      // Construct using sharebase.Bytom.BytomMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        jobid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        workerhashid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        sharediff_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        blkbits_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        height_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        ip_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        combinedHeader_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000100);
        userid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000400);
        extuserid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000800);
        bitsreached_ = 0;
        bitField0_ = (bitField0_ & ~0x00001000);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sharebase.Bytom.internal_static_sharebase_BytomMsg_descriptor;
      }

      @java.lang.Override
      public sharebase.Bytom.BytomMsg getDefaultInstanceForType() {
        return sharebase.Bytom.BytomMsg.getDefaultInstance();
      }

      @java.lang.Override
      public sharebase.Bytom.BytomMsg build() {
        sharebase.Bytom.BytomMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public sharebase.Bytom.BytomMsg buildPartial() {
        sharebase.Bytom.BytomMsg result = new sharebase.Bytom.BytomMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.jobid_ = jobid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.workerhashid_ = workerhashid_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.sharediff_ = sharediff_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.blkbits_ = blkbits_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.height_ = height_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.ip_ = ip_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.combinedHeader_ = combinedHeader_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.userid_ = userid_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.extuserid_ = extuserid_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.bitsreached_ = bitsreached_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sharebase.Bytom.BytomMsg) {
          return mergeFrom((sharebase.Bytom.BytomMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sharebase.Bytom.BytomMsg other) {
        if (other == sharebase.Bytom.BytomMsg.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasJobid()) {
          setJobid(other.getJobid());
        }
        if (other.hasWorkerhashid()) {
          setWorkerhashid(other.getWorkerhashid());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasSharediff()) {
          setSharediff(other.getSharediff());
        }
        if (other.hasBlkbits()) {
          setBlkbits(other.getBlkbits());
        }
        if (other.hasHeight()) {
          setHeight(other.getHeight());
        }
        if (other.hasIp()) {
          bitField0_ |= 0x00000080;
          ip_ = other.ip_;
          onChanged();
        }
        if (other.hasCombinedHeader()) {
          setCombinedHeader(other.getCombinedHeader());
        }
        if (other.hasUserid()) {
          setUserid(other.getUserid());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasExtuserid()) {
          setExtuserid(other.getExtuserid());
        }
        if (other.hasBitsreached()) {
          setBitsreached(other.getBitsreached());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasVersion()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        sharebase.Bytom.BytomMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (sharebase.Bytom.BytomMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int version_ ;
      /**
       * <code>required uint32 version = 1;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 version = 1;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>required uint32 version = 1;</code>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 version = 1;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0;
        onChanged();
        return this;
      }

      private long jobid_ ;
      /**
       * <code>optional uint64 jobid = 2;</code>
       */
      public boolean hasJobid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint64 jobid = 2;</code>
       */
      public long getJobid() {
        return jobid_;
      }
      /**
       * <code>optional uint64 jobid = 2;</code>
       */
      public Builder setJobid(long value) {
        bitField0_ |= 0x00000002;
        jobid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 jobid = 2;</code>
       */
      public Builder clearJobid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        jobid_ = 0L;
        onChanged();
        return this;
      }

      private long workerhashid_ ;
      /**
       * <code>optional sint64 workerhashid = 3;</code>
       */
      public boolean hasWorkerhashid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional sint64 workerhashid = 3;</code>
       */
      public long getWorkerhashid() {
        return workerhashid_;
      }
      /**
       * <code>optional sint64 workerhashid = 3;</code>
       */
      public Builder setWorkerhashid(long value) {
        bitField0_ |= 0x00000004;
        workerhashid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint64 workerhashid = 3;</code>
       */
      public Builder clearWorkerhashid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        workerhashid_ = 0L;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>optional sint64 timestamp = 4;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional sint64 timestamp = 4;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional sint64 timestamp = 4;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000008;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint64 timestamp = 4;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000008);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private long sharediff_ ;
      /**
       * <code>optional uint64 sharediff = 5;</code>
       */
      public boolean hasSharediff() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional uint64 sharediff = 5;</code>
       */
      public long getSharediff() {
        return sharediff_;
      }
      /**
       * <code>optional uint64 sharediff = 5;</code>
       */
      public Builder setSharediff(long value) {
        bitField0_ |= 0x00000010;
        sharediff_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 sharediff = 5;</code>
       */
      public Builder clearSharediff() {
        bitField0_ = (bitField0_ & ~0x00000010);
        sharediff_ = 0L;
        onChanged();
        return this;
      }

      private long blkbits_ ;
      /**
       * <code>optional uint64 blkbits = 6;</code>
       */
      public boolean hasBlkbits() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional uint64 blkbits = 6;</code>
       */
      public long getBlkbits() {
        return blkbits_;
      }
      /**
       * <code>optional uint64 blkbits = 6;</code>
       */
      public Builder setBlkbits(long value) {
        bitField0_ |= 0x00000020;
        blkbits_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 blkbits = 6;</code>
       */
      public Builder clearBlkbits() {
        bitField0_ = (bitField0_ & ~0x00000020);
        blkbits_ = 0L;
        onChanged();
        return this;
      }

      private long height_ ;
      /**
       * <code>optional uint64 height = 7;</code>
       */
      public boolean hasHeight() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional uint64 height = 7;</code>
       */
      public long getHeight() {
        return height_;
      }
      /**
       * <code>optional uint64 height = 7;</code>
       */
      public Builder setHeight(long value) {
        bitField0_ |= 0x00000040;
        height_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 height = 7;</code>
       */
      public Builder clearHeight() {
        bitField0_ = (bitField0_ & ~0x00000040);
        height_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object ip_ = "";
      /**
       * <code>optional string ip = 8;</code>
       */
      public boolean hasIp() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string ip = 8;</code>
       */
      public java.lang.String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ip_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ip = 8;</code>
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        java.lang.Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ip = 8;</code>
       */
      public Builder setIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ip = 8;</code>
       */
      public Builder clearIp() {
        bitField0_ = (bitField0_ & ~0x00000080);
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ip = 8;</code>
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        ip_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString combinedHeader_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes combinedHeader = 9;</code>
       */
      public boolean hasCombinedHeader() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional bytes combinedHeader = 9;</code>
       */
      public com.google.protobuf.ByteString getCombinedHeader() {
        return combinedHeader_;
      }
      /**
       * <code>optional bytes combinedHeader = 9;</code>
       */
      public Builder setCombinedHeader(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        combinedHeader_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes combinedHeader = 9;</code>
       */
      public Builder clearCombinedHeader() {
        bitField0_ = (bitField0_ & ~0x00000100);
        combinedHeader_ = getDefaultInstance().getCombinedHeader();
        onChanged();
        return this;
      }

      private int userid_ ;
      /**
       * <code>optional sint32 userid = 10;</code>
       */
      public boolean hasUserid() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional sint32 userid = 10;</code>
       */
      public int getUserid() {
        return userid_;
      }
      /**
       * <code>optional sint32 userid = 10;</code>
       */
      public Builder setUserid(int value) {
        bitField0_ |= 0x00000200;
        userid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 userid = 10;</code>
       */
      public Builder clearUserid() {
        bitField0_ = (bitField0_ & ~0x00000200);
        userid_ = 0;
        onChanged();
        return this;
      }

      private int status_ ;
      /**
       * <code>optional sint32 status = 11;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional sint32 status = 11;</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>optional sint32 status = 11;</code>
       */
      public Builder setStatus(int value) {
        bitField0_ |= 0x00000400;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 status = 11;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000400);
        status_ = 0;
        onChanged();
        return this;
      }

      private int extuserid_ ;
      /**
       * <pre>
       * Extended uid in single-user mode. May not be set.
       * </pre>
       *
       * <code>optional sint32 extuserid = 12;</code>
       */
      public boolean hasExtuserid() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <pre>
       * Extended uid in single-user mode. May not be set.
       * </pre>
       *
       * <code>optional sint32 extuserid = 12;</code>
       */
      public int getExtuserid() {
        return extuserid_;
      }
      /**
       * <pre>
       * Extended uid in single-user mode. May not be set.
       * </pre>
       *
       * <code>optional sint32 extuserid = 12;</code>
       */
      public Builder setExtuserid(int value) {
        bitField0_ |= 0x00000800;
        extuserid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Extended uid in single-user mode. May not be set.
       * </pre>
       *
       * <code>optional sint32 extuserid = 12;</code>
       */
      public Builder clearExtuserid() {
        bitField0_ = (bitField0_ & ~0x00000800);
        extuserid_ = 0;
        onChanged();
        return this;
      }

      private int bitsreached_ ;
      /**
       * <code>optional uint32 bitsreached = 13;</code>
       */
      public boolean hasBitsreached() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>optional uint32 bitsreached = 13;</code>
       */
      public int getBitsreached() {
        return bitsreached_;
      }
      /**
       * <code>optional uint32 bitsreached = 13;</code>
       */
      public Builder setBitsreached(int value) {
        bitField0_ |= 0x00001000;
        bitsreached_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 bitsreached = 13;</code>
       */
      public Builder clearBitsreached() {
        bitField0_ = (bitField0_ & ~0x00001000);
        bitsreached_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sharebase.BytomMsg)
    }

    // @@protoc_insertion_point(class_scope:sharebase.BytomMsg)
    private static final sharebase.Bytom.BytomMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sharebase.Bytom.BytomMsg();
    }

    public static sharebase.Bytom.BytomMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<BytomMsg>
        PARSER = new com.google.protobuf.AbstractParser<BytomMsg>() {
      @java.lang.Override
      public BytomMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BytomMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BytomMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BytomMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public sharebase.Bytom.BytomMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sharebase_BytomMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sharebase_BytomMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013bytom.proto\022\tsharebase\"\363\001\n\010BytomMsg\022\017\n" +
      "\007version\030\001 \002(\r\022\r\n\005jobid\030\002 \001(\004\022\024\n\014workerh" +
      "ashid\030\003 \001(\022\022\021\n\ttimestamp\030\004 \001(\022\022\021\n\tshared" +
      "iff\030\005 \001(\004\022\017\n\007blkbits\030\006 \001(\004\022\016\n\006height\030\007 \001" +
      "(\004\022\n\n\002ip\030\010 \001(\t\022\026\n\016combinedHeader\030\t \001(\014\022\016" +
      "\n\006userid\030\n \001(\021\022\016\n\006status\030\013 \001(\021\022\021\n\textuse" +
      "rid\030\014 \001(\021\022\023\n\013bitsreached\030\r \001(\r"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_sharebase_BytomMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sharebase_BytomMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sharebase_BytomMsg_descriptor,
        new java.lang.String[] { "Version", "Jobid", "Workerhashid", "Timestamp", "Sharediff", "Blkbits", "Height", "Ip", "CombinedHeader", "Userid", "Status", "Extuserid", "Bitsreached", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
